"""
NSF Critical Controls - AWS Library Module

Common utilities for AWS security audits.
"""

from .aws_common import (
    AuditContext,
    AuditPermissionError,
    add_common_arguments,
    build_role_arn,
    build_session,
    current_date,
    ensure_directory,
    format_issues,
    get_all_accounts,
    get_all_regions,
    get_identity_stores,
    is_permission_error,
    permission_failure_count,
    permission_failures,
    warn_permission_error,
    load_csv,
    load_json_config,
    load_yaml,
    parse_accounts_arg,
    parse_formats_arg,
    parse_regions_arg,
    previous_date,
    resolve_output_dir,
    resolve_role,
    save_csv,
    save_json,
    save_results,
    save_text,
    save_yaml,
    validate_account_id,
)

__all__ = [
    'AuditContext',
    'AuditPermissionError',
    'add_common_arguments',
    'build_role_arn',
    'build_session',
    'current_date',
    'ensure_directory',
    'format_issues',
    'get_all_accounts',
    'get_all_regions',
    'get_identity_stores',
    'is_permission_error',
    'permission_failure_count',
    'permission_failures',
    'warn_permission_error',
    'load_csv',
    'load_json_config',
    'load_yaml',
    'parse_accounts_arg',
    'parse_formats_arg',
    'parse_regions_arg',
    'previous_date',
    'resolve_output_dir',
    'resolve_role',
    'save_csv',
    'save_json',
    'save_results',
    'save_text',
    'save_yaml',
    'validate_account_id',
]
